name: Stats
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
        
          user: konradrundfunk
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_traffic: yes
          repositories: 500
